export default {
  first: [
    'The Evil',
    'The Mad',
    'The Big',
    'The Dangerous',
    'The Ghostly',
    'Unstoppable',
    'Phantom',
    'The Vile',
    'The Dark',
    'The Bloody',
    'The Atomic',
    'The Ugly',
    'The Brutal',
    'The Unforeseen',
    'The White',
    'The Crazy',
    'The Slimy',
    'The Psychic',
    'Scary',
    'The Wild',
    'The Hairy',
    'The invisible',
    'The Grand',
    'The Terrifying',
    'The Poison',
    'The Black',
    'The Red',
    'The Cursed',
    'The Wicked',
  ],
  last: [
    'Shadow',
    'Skull',
    'Wizard',
    'Witch',
    'Ninja',
    'Sidekick',
    'Devil',
    'Lord',
    'Slayer',
    'Cat',
    'Bat',
    'Hound',
    'Joker',
    'Fairy',
    'Spider',
    'Vampire',
    'Mutant',
    'Claw',
    'Clown',
    'Monster ',
    'Werewolf',
    'Robot',
    'Creature',
    'Goblin',
    'Nurse',
    'Assasin',
    'Troll',
    'Bear',
    'King ',
    'Queen',
    'Knight',
    'Professor ',
    'Doktor',
    'Captain',
  ],
}
