export default {
  first: [
    'Crimson',
    'Doctor',
    'Drunken',
    'Grumpy',
    'Master',
    'Phantom',
    'Scary',
    'The Absent',
    'The Accidental',
    'The Adorable',
    'The Aggressive',
    'The Alien',
    'The Ancient',
    'The Anxious',
    'The Armed',
    'The Atomic',
    'The Awful',
    'The Bad',
    'The Big',
    'The Bitter',
    'The Bizarre',
    'The Bloody',
    'The Brass',
    'The Broken',
    'The Brutal',
    'The Careless',
    'The Colossal',
    'The Confident',
    'The Cowardly',
    'The Crazy',
    'The Creepy',
    'The Cruel',
    'The Curious',
    'The Cursed',
    'The Dangerous',
    'The Dark',
    'The Dazzling',
    'The Dead',
    'The Defiant',
    'The Delirious',
    'The Deranged',
    'The Devilish',
    'The Diamond',
    'The Dirty',
    'The Dramatic',
    'The Drunken',
    'The Dynamic',
    'The Eager',
    'The Electric',
    'The Elegant',
    'The Elite',
    'The Evil',
    'The Excited',
    'The False',
    'The Famous',
    'The Fearless',
    'The Fiery',
    'The Filthy',
    'The Fire',
    'The First',
    'The Flashy',
    'The Fluffy',
    'The Foolish',
    'The Frightening',
    'The Frozen',
    'The Galactic',
    'The Ghastly',
    'The Ghost',
    'The Ghostly',
    'The Giant',
    'The Gifted',
    'The Goofy',
    'The Grand',
    'The Greasy',
    'The Groovy',
    'The Gruesome',
    'The Grumpy',
    'The Gullible',
    'The Hairy',
    'The Harsh',
    'The Hissing',
    'The Hollow',
    'The Huge',
    'The Hungry',
    'The Hypnotic',
    'The Ice',
    'The Impossible',
    'The Incredible',
    'The Infamous',
    'The invisible',
    'The Iron',
    'The Jagged',
    'The Jealous',
    'The Jolly',
    'The Last',
    'The Laughing',
    'The Lazy',
    'The Lean',
    'The Lonely',
    'The Loud',
    'The Lucky',
    'The Lying',
    'The Mad',
    'The Maniacal',
    'The Marked',
    'The Massive',
    'The Mean',
    'The Messy',
    'The Mighty',
    'The Misty',
    'The Molten',
    'The Mysterious',
    'The Nasty',
    'The Naughty',
    'The Needy',
    'The Nervous',
    'The Nifty',
    'The Nimble',
    'The Nuclear',
    'The Obnoxious',
    'The Odd',
    'The Poison',
    'The Proud',
    'The Psychic',
    'The Psychotic',
    'The Quantum',
    'The Quick',
    'The Quiet',
    'The Rabid',
    'The Rebellious',
    'The Repulsive',
    'The Rotten',
    'The Ruthless',
    'The Sad',
    'The Scary',
    'The Secret',
    'The Shaggy',
    'The Sick',
    'The Skilled',
    'The Slimy',
    'The Sly',
    'The Smelly',
    'The Smiling',
    'The Smoooth',
    'The Spectacular',
    'The Spooky',
    'The Storm',
    'The Swift',
    'The Talented',
    'The Terrible',
    'The Terrific',
    'The Terrifying',
    'The Threatening',
    'The Towering',
    'The Tricky',
    'The Ugly',
    'The Undefeated',
    'The Unforeseen',
    'The Unknown',
    'The Unnatural',
    'The Unusual',
    'The Vengeful',
    'The Venomous',
    'The Vile',
    'The Wacky',
    'The Wandering',
    'The Whispering',
    'The Wicked',
    'The Wild',
    'The Wise',
    'The Wretched',
    'Unstoppable',
    'Wacky',
  ],
  last: [
    'Agent',
    'Amazon',
    'Android',
    'Ant',
    'Armadillo',
    'Arsonist',
    'Artist',
    'Assasin',
    'Assassin',
    'Bandit',
    'Banshee',
    'Barbarian',
    'Baron',
    'Bat',
    'Bear',
    'Beast',
    'Beetle',
    'Brute',
    'Buffoon',
    'Burglar',
    'Butcher',
    'Captain',
    'Cat',
    'Charmer',
    'Cheat',
    'Cheetah',
    'Chief',
    'Claw',
    'Clown',
    'Condor',
    'Conjurer',
    'Crane',
    'Creature',
    'Cricket',
    'Criminal',
    'Crook',
    'Crow',
    'Devil',
    'Doktor',
    'Dragonfly',
    'Duke',
    'Eagle',
    'Enchanter',
    'Fairy',
    'Falcon',
    'Fiend',
    'Fighter',
    'Fool',
    'Fox',
    'Freak',
    'Gangster',
    'Gargoyle',
    'Genius',
    'Giant',
    'Gloom',
    'Goblin',
    'Gorilla',
    'Grasshopper',
    'Harlequin',
    'Haunt',
    'Hawk',
    'Hijacker',
    'Hornet',
    'Horror',
    'Hound',
    'Ibis',
    'Illusionist',
    'Jackal',
    'Jester',
    'Joker',
    'King ',
    'Knight',
    'Leopard',
    'Lion',
    'Lord',
    'Lynx',
    'Macaw',
    'Mage',
    'Magician',
    'Mantis',
    'Mastermind',
    'Merlin',
    'Mime',
    'Mole',
    'Monarch',
    'Mongoose',
    'Monster ',
    'Monster',
    'Morpher',
    'Moth',
    'Mugger',
    'Mutant',
    'Nighthawk',
    'Nightowl',
    'Ninja',
    'Nurse',
    'Owl',
    'Ox',
    'Panther',
    'Phoenix',
    'Pirate',
    'Plunderer',
    'Prankster',
    'Prince',
    'Prodigy',
    'Professor ',
    'Prophet',
    'Puma',
    'Queen',
    'Raccoon',
    'Rhino',
    'Robber',
    'Robot',
    'Sage',
    'Savage',
    'Scorpion',
    'Scout',
    'Seer',
    'Sentinel',
    'Shade',
    'Shadow',
    'Shadow',
    'Shaman',
    'Sidekick',
    'Siren',
    'Skull',
    'Slayer',
    'Smasher',
    'Snipe',
    'Specter',
    'Spider',
    'Spirit',
    'Spy',
    'Stealer',
    'Swan',
    'Swindler',
    'Swine',
    'Termite',
    'Thief',
    'Tiger',
    'Trickster',
    'Troll',
    'Vampire',
    'Villain',
    'Vindicator',
    'Vulture',
    'Warrior',
    'Wasp',
    'Werewolf',
    'Witch',
    'Wizard',
    'Wolf',
    'Wolverine',
    'Wraith',
    'Zombie',
  ],
}
